### Creating a matrix

In [ ]:
#Lists of Lists:
matrix = [[9, 6, 8],
          [6, 5, 9],
          [3, 2, 2]]


In [ ]:
#to install numpy in notebook

#!pip install numpy

In [2]:
#NumPy Library
import numpy as np

matrix = np.array([[9, 6, 8],
                   [6, 5, 9],
                   [3, 2, 2]])

In [3]:
print(matrix)

[[9 6 8]
 [6 5 9]
 [3 2 2]]


In [4]:
#NumPy Functions
import numpy as np

zero_matrix = np.zeros((2, 2))
print(zero_matrix)

[[0. 0.]
 [0. 0.]]


In [6]:
one_matrix = np.ones((3, 2))
print(one_matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
random_matrix = np.random.rand(3, 2)
print(random_matrix)

[[0.69509681 0.13170359]
 [0.40592545 0.63222216]
 [0.83564657 0.05351278]]


In [8]:
#List Comprehension:
matrix = [[column for column in range(2)] for row in range(2)]

print(matrix)

[[0, 1], [0, 1]]


### Addition and Subtraction

In [9]:
import numpy as np

# Define two matrices A and B
A = np.array([[3, 5, 2],
              [4, 1, 3],
              [6, 2, 1]])

B = np.array([[4, 2, 1],
              [1, 5, 3],
              [4, 1, 3]])

In [10]:
# Perform matrix addition subtrcation
C = A + B
D = A-B
print("Addition of two matrices")
print(C)

print("Subtraction of two matrices")
print(D)

Addition of two matrices
[[ 7  7  3]
 [ 5  6  6]
 [10  3  4]]
Subtraction of two matrices
[[-1  3  1]
 [ 3 -4  0]
 [ 2  1 -2]]


In [11]:
#using NumPy
import numpy as np

print("Addition of two matrices")
print(np.add(A, B))
print("Subtraction of two matrices")
print(np.subtract(A, B))

Addition of two matrices
[[ 7  7  3]
 [ 5  6  6]
 [10  3  4]]
Subtraction of two matrices
[[-1  3  1]
 [ 3 -4  0]
 [ 2  1 -2]]


### Multiplication

In [12]:
#using element-wise method
import numpy as np

C = np.dot(A, B)
print(C)

[[25 33 24]
 [29 16 16]
 [30 23 15]]


In [13]:
#using row-column method
import numpy as np

C = np.matmul(A, B)
print(C)

D = A@B
print(D)

[[25 33 24]
 [29 16 16]
 [30 23 15]]
[[25 33 24]
 [29 16 16]
 [30 23 15]]


### Transpose

In [14]:
#let there be a matrix A, its transpose will be

AT = A.T
print(AT)

[[3 4 6]
 [5 1 2]
 [2 3 1]]


In [15]:
ta = A.transpose()
print(ta)

[[3 4 6]
 [5 1 2]
 [2 3 1]]


### Inverse

In [16]:
#using numpy
import numpy as np

inverse_A = np.linalg.inv(A)
print(inverse_A)

[[-0.08474576 -0.01694915  0.22033898]
 [ 0.23728814 -0.15254237 -0.01694915]
 [ 0.03389831  0.40677966 -0.28813559]]
